export const FETCH_MARKERSINFO_INIT = 'FETCH_MARKERSINFO_INIT';
export const FETCH_MARKERSINFO_SUCCESS = 'FETCH_MARKERSINFO_SUCCESS';
export const FETCH_MARKERSINFO_FAIL = 'FETCH_MARKERSINFO_FAIL';
export const FETCH_MARKERSINFO_START = 'FETCH_MARKERSINFO_START';